# Generated by Django 5.1 on 2024-08-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_maincat_subcat1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcat1',
            new_name='Subcat',
        ),
    ]
