# Generated by Django 5.1 on 2024-08-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_subcat1_subcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('rating', models.IntegerField(default=1, max_length=5)),
                ('Subcat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.subcat')),
            ],
        ),
    ]
