# Generated by Django 5.1 on 2024-08-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Maincat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.maincat'),
        ),
    ]
