# Generated by Django 5.1 on 2024-08-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_maincat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincat',
            options={},
        ),
    ]
