# Generated by Django 5.1 on 2024-08-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_maincat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Maincat',
            new_name='maincat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Subcat',
            new_name='subcat',
        ),
    ]
