# Generated by Django 5.1 on 2024-08-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_maincat_product_maincat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat',
            name='maincat',
        ),
    ]
