# Generated by Django 5.1 on 2024-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
